server:
  port: 8081
  servlet:
    context-path: /ms-auth

spring:
  application:
    name: ms-auth
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    root: info
    az.guavapay.auth: debug

client:
 ms-user:
  endpoint: http://userApp:8082/ms-user