version: '3'

services:
  apiGateWayApp:
    image: 'ms-api-gateway:latest'
    build:
      context: .
    container_name: api_gateway_app
    ports:
      - 8080:8080

networks:
  default:
    external:
      name: guavapay

